CREATE TABLE IF NOT EXISTS monitored_computer (
  computer_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  computer_uuid VARCHAR(100) NOT NULL,
  computer_name VARCHAR(100) NOT NULL,
  os_name VARCHAR(100) DEFAULT NULL,
  os_version VARCHAR(100) DEFAULT NULL,
  os_architecture VARCHAR(32) DEFAULT NULL,
  cpu_name VARCHAR(255) DEFAULT NULL,
  cpu_usage_percent DECIMAL(5,2) DEFAULT NULL,
  ram_used_bytes BIGINT UNSIGNED DEFAULT NULL,
  ram_total_bytes BIGINT UNSIGNED DEFAULT NULL,
  disk_used_bytes BIGINT UNSIGNED DEFAULT NULL,
  disk_total_bytes BIGINT UNSIGNED DEFAULT NULL,
  uptime_seconds BIGINT UNSIGNED DEFAULT NULL,
  metrics_updated_at DATETIME(3) DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  app_version VARCHAR(32) DEFAULT NULL,
  status ENUM('ONLINE', 'OFFLINE') NOT NULL DEFAULT 'OFFLINE',
  last_seen DATETIME DEFAULT NULL,
  connected_at DATETIME DEFAULT NULL,
  disconnected_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (computer_id),
  UNIQUE KEY uk_user_computer_uuid (user_id, computer_uuid),
  KEY idx_computer_user_id (user_id),
  KEY idx_computer_status (status),
  KEY idx_computer_last_seen (last_seen),
  CONSTRAINT fk_monitored_computer_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS machine_logs (
  log_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  computer_id BIGINT UNSIGNED NOT NULL,
  log_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  level ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL') NOT NULL DEFAULT 'INFO',
  message TEXT NOT NULL,
  PRIMARY KEY (log_id),
  KEY idx_machine_logs_computer_id (computer_id),
  KEY idx_machine_logs_time (log_time),
  KEY idx_machine_logs_level (level),
  KEY idx_machine_logs_computer_time (computer_id, log_time),
  CONSTRAINT fk_machine_logs_computer FOREIGN KEY (computer_id) REFERENCES monitored_computer (computer_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
