ALTER TABLE monitored_computer
  ADD COLUMN IF NOT EXISTS os_name VARCHAR(100) DEFAULT NULL AFTER computer_name,
  ADD COLUMN IF NOT EXISTS os_version VARCHAR(100) DEFAULT NULL AFTER os_name,
  ADD COLUMN IF NOT EXISTS os_architecture VARCHAR(32) DEFAULT NULL AFTER os_version,
  ADD COLUMN IF NOT EXISTS cpu_name VARCHAR(255) DEFAULT NULL AFTER os_architecture,
  ADD COLUMN IF NOT EXISTS cpu_usage_percent DECIMAL(5,2) DEFAULT NULL AFTER cpu_name,
  ADD COLUMN IF NOT EXISTS ram_used_bytes BIGINT UNSIGNED DEFAULT NULL AFTER cpu_usage_percent,
  ADD COLUMN IF NOT EXISTS ram_total_bytes BIGINT UNSIGNED DEFAULT NULL AFTER ram_used_bytes,
  ADD COLUMN IF NOT EXISTS disk_used_bytes BIGINT UNSIGNED DEFAULT NULL AFTER ram_total_bytes,
  ADD COLUMN IF NOT EXISTS disk_total_bytes BIGINT UNSIGNED DEFAULT NULL AFTER disk_used_bytes,
  ADD COLUMN IF NOT EXISTS uptime_seconds BIGINT UNSIGNED DEFAULT NULL AFTER disk_total_bytes,
  ADD COLUMN IF NOT EXISTS metrics_updated_at DATETIME(3) DEFAULT NULL AFTER uptime_seconds;